# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbs_renmo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_token', models.CharField(max_length=200)),
                ('stripe_token', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbs_renmo.User')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_date', models.DateField()),
                ('CNY_amount', models.IntegerField(max_length=30)),
                ('fx_rate', models.FloatField(max_length=30)),
                ('seller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbs_renmo.User')),
            ],
        ),
    ]
